Teding/feat/compression
sprngr/aseprite-record pull request #8
Opened 2022-05-01 17:24 UTC by thomaseding

- Use actual Lua class syntax. (I finally read up on Lua 🎉)
- Avoids recording duplicate image sequences.

2022-05-03 17:32 UTC, sprngr commented on .lib/record-core.lua
> +    end
@thomaseding  We can just omit the else case here since it isn't doing anything. I feel like it is clear that it's only incrementing on image change.

2022-05-03 20:40 UTC, sprngr commented on .lib/record-core.lua
> +    -- have a computer that is average by 2022 standards.
Ill be sure to beat this up as I have a computer considered average by 2012 standard.

2022-05-04 20:00 UTC, thomaseding commented
Eeep!! I forgot to close the files I opened. Also check if any file opens.

2022-05-07 00:29 UTC, sprngr commented on .lib/record-core.lua
> +function show_error(error_msg)
good catch on variable naming

2022-05-07 01:55 UTC, sprngr commented on Command Palette.lua
> +    local path = snapshot:get_recording_image_path_at_index(0)
```suggestion
    local path = snapshot:get_recording_image_path(0)
```

2022-05-07 01:56 UTC, sprngr commented on .lib/record-core.lua
> +    -- have a computer that is average by 2022 standards.
```suggestion
```
Can prune these comments from the code, is preferable to maintain these types of artifacts in PR comments for history tracking.

2022-05-07 01:56 UTC, sprngr commented on .lib/record-core.lua
> +    -- snapshot (where N is the current snapshot index).
```suggestion
```
Can prune these comments from the code, is preferable to maintain these types of artifacts in PR comments for history tracking.

2022-05-07 02:00 UTC, sprngr commented on .lib/record-core.lua
> +    -- have a computer that is average by 2022 standards.
✅  Ran through a gambit of:
- Image creation
- cropping
- painting
- fills
- moving
- resizing

2022-05-07 02:08 UTC, sprngr requested changes
Ran through a bunch of testing on my end, performance seems good. Just a few things that need to be addressed including an incorrect method reference.

2022-05-13 16:42 UTC, sprngr commented
@thomaseding Thanks for updating. Going to pull it down later today and do another pass through.

2022-05-14 02:38 UTC, sprngr approved these changes
@thomaseding Everything looks good to me. Going to merge it in and get a release tagged and prepare an update to go out to itch. Thank you for contributing :shipit:

2022-05-14 02:38 UTC, merged